apiVersion: v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: mongodb
spec:
  replicas: {{ .Values.deployment.replicas}}
  selector:
    matchLabels:
      project: roboshop
      tier: db
      component: mongodb

  # Pod definition
  template:
    metadata:
      labels:
        project: roboshop
        tier: db
        component: mongodb
    spec:
      containers:
      - name: mongodb
        image: "{{ .Values.deployment.imageName }}:{{ .Values.deployment.imageVersion }}"
