apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: mongodb
spec:
  selector:
    # labels are used as selectors
    project: roboshop
    tier: db
    component: mongodb
  ports:
  - protocol: TCP
    port: 27017 # servie port
    targetPort: 27017 # container port